# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Conn1'
    subscriptionId: 'fb4c95c5-2774-4cbd-907e-d9685748ba89'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'armRSG021'
    location: 'Southeast Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-windows/azuredeploy.json'
    overrideParameters: '-adminUsername "username" -adminPassword "Password@1123" -dnsLabelPrefix dns001'
    deploymentMode: 'Incremental'

  displayName: 'Run a multi-line script'
